name: env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - blinker=1.9.0
  - certifi=2024.12.14
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - filelock=3.16.1
  - flask=3.1.0
  - fsspec=2024.12.0
  - huggingface-hub=0.27.0
  - idna=3.10
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - markupsafe=3.0.2
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.2.1
  - packaging=24.2
  - pyyaml=6.0.2
  - regex=2024.11.6
  - requests=2.32.3
  - safetensors=0.5.0
  - setuptools=75.6.0
  - sympy=1.13.1
  - tokenizers=0.21.0
  - torch=2.5.1
  - tqdm=4.67.1
  - transformers=4.47.1
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - werkzeug=3.1.3
